/**
 * ARM Linker Listing file parser.
 * Parses files generated by armlink --list option.
 * Supports ARM Compiler 5 (armcc) and ARM Compiler 6 (armclang) output formats.
 */

import { MemoryRegion, ElfSection, SectionSummary, MemoryUsage, MemoryUsageEntry } from './elfParser';

export interface ArmLinkEntry {
    addr: number;
    size: number;
    kind: string;     // Code, Data, Zero
    attr: string;     // RO, RW, ZI
    object: string;   // e.g., "main.o" or "lludiv5.o" (from lib(obj) pattern)
    section: string;  // e.g., ".text"
    func: string;     // function/symbol name extracted from section token (e.g., "_ZN1TEST10Func")
}

export interface ArmLinkExecRegion {
    name: string;
    execBase: number;
    size: number;       // current used size
    maxSize: number;    // total available size
    entries: ArmLinkEntry[];
}

export interface ArmLinkListResult {
    execRegions: ArmLinkExecRegion[];
    entryPoint: number;
    totals: {
        roSize: number;
        rwSize: number;
        romSize: number;
    };
}

// Regex patterns — flexible whitespace for cross-version compatibility
const EXEC_REGION_RE = /Execution\s+Region\s+(\S+)\s+\((.+)\)/i;
const LOAD_REGION_RE = /Load\s+Region\s+\S+\s+\(/i;
const ENTRY_RE = /^\s+(0x[0-9a-fA-F]+)\s+(0x[0-9a-fA-F]+)\s+(Code|Data|Zero)\s+(RO|RW|ZI)\b/i;
const PAD_RE = /^\s+0x[0-9a-fA-F]+\s+0x[0-9a-fA-F]+\s+PAD\b/i;
const OBJ_SECTION_RE = /(\S+)\(([^)]*)\)\s*$/;
const ENTRY_POINT_RE = /Image\s+Entry\s+point\s*:\s*(0x[0-9a-fA-F]+)/i;
const RO_TOTAL_RE = /Total\s+RO\s+Size[^0-9]*(\d+)\s*\(/i;
const RW_TOTAL_RE = /Total\s+RW\s+Size[^0-9]*(\d+)\s*\(/i;
const ROM_TOTAL_RE = /Total\s+ROM\s+Size[^0-9]*(\d+)\s*\(/i;
const SEPARATOR_RE = /^={4,}\s*$/;

/** Known section prefixes — strip these to extract function name */
const SECTION_PREFIXES = ['.text.', '.rodata.', '.data.', '.bss.', '.constdata.', '.ARM.'];

function extractFunc(sectionToken: string): string {
    for (const prefix of SECTION_PREFIXES) {
        if (sectionToken.startsWith(prefix)) {
            return sectionToken.substring(prefix.length);
        }
    }
    // No known prefix — return the whole token as-is
    return sectionToken;
}

/**
 * Parse "Exec base: 0x..." or "Base: 0x..." style parameters from Execution Region header.
 * Handles both AC5 and AC6 formats.
 */
function parseRegionParams(paramStr: string): { execBase: number; size: number; maxSize: number } {
    let execBase = 0, size = 0, maxSize = 0;

    // AC6: "Exec base: 0x..." / AC5: "Base: 0x..."
    const baseMatch = /(?:Exec\s+)?[Bb]ase:\s*(0x[0-9a-fA-F]+)/i.exec(paramStr);
    if (baseMatch) { execBase = parseInt(baseMatch[1], 16); }

    const sizeMatch = /\bSize:\s*(0x[0-9a-fA-F]+)/i.exec(paramStr);
    if (sizeMatch) { size = parseInt(sizeMatch[1], 16); }

    const maxMatch = /\bMax:\s*(0x[0-9a-fA-F]+)/i.exec(paramStr);
    if (maxMatch) { maxSize = parseInt(maxMatch[1], 16); }

    return { execBase, size, maxSize };
}

/**
 * Parse ARM linker listing file content.
 */
export function parseArmLinkList(content: string): ArmLinkListResult {
    const lines = content.split(/\r?\n/);
    const execRegions: ArmLinkExecRegion[] = [];
    let currentExecRegion: ArmLinkExecRegion | null = null;
    let entryPoint = 0;
    const totals = { roSize: 0, rwSize: 0, romSize: 0 };

    for (const line of lines) {
        // Entry point
        const epMatch = ENTRY_POINT_RE.exec(line);
        if (epMatch) {
            entryPoint = parseInt(epMatch[1], 16);
            continue;
        }

        // Load Region resets current exec region context
        if (LOAD_REGION_RE.test(line)) {
            currentExecRegion = null;
            continue;
        }

        // Execution Region header
        const erMatch = EXEC_REGION_RE.exec(line);
        if (erMatch) {
            const params = parseRegionParams(erMatch[2]);
            currentExecRegion = {
                name: erMatch[1],
                execBase: params.execBase,
                size: params.size,
                maxSize: params.maxSize,
                entries: [],
            };
            execRegions.push(currentExecRegion);
            continue;
        }

        // Section entries (only within an execution region)
        if (currentExecRegion) {
            const entryMatch = ENTRY_RE.exec(line);
            if (entryMatch) {
                const addr = parseInt(entryMatch[1], 16);
                const sz = parseInt(entryMatch[2], 16);
                const kind = entryMatch[3];
                const attr = entryMatch[4].toUpperCase();

                // Extract idx, section token, and object(section) from the rest of the line
                // Format: idx  sectionToken  library(object)
                //   e.g.: 2899  .text._ZN1TEST10Func  c_2.l(lludiv5.o)
                //   or:   2899  main.o(.text)
                const rest = line.substring(entryMatch[0].length);
                const objMatch = OBJ_SECTION_RE.exec(rest);

                let object = '';
                let section = '';
                let func = '';
                if (objMatch) {
                    // lib(obj) pattern at end: e.g., "c_2.l(lludiv5.o)" or "main.o(.text)"
                    const libOrObj = objMatch[1];    // "c_2.l" or "main.o"
                    const inParen = objMatch[2];     // "lludiv5.o" or ".text"

                    if (inParen.endsWith('.o')) {
                        // library(object.o) pattern — object is inside parens
                        object = inParen;
                    } else {
                        // object(.section) pattern — object is before parens
                        object = libOrObj;
                        section = inParen;
                    }

                    // Extract section token between idx and the lib(obj) part
                    const beforeObj = rest.substring(0, objMatch.index).trim();
                    const tokens = beforeObj.split(/\s+/);
                    // tokens: [idx, sectionToken?] — skip numeric idx
                    const sectionToken = tokens.find(t => !/^\d+$/.test(t) && t.length > 0);
                    if (sectionToken) {
                        if (!section) {
                            // Take base section name from token prefix (e.g., ".text" from ".text._ZN...")
                            for (const prefix of SECTION_PREFIXES) {
                                if (sectionToken.startsWith(prefix.slice(0, -1))) {
                                    section = prefix.slice(0, -1); // ".text"
                                    break;
                                }
                            }
                            if (!section) { section = sectionToken; }
                        }
                        func = extractFunc(sectionToken);
                    }
                } else {
                    // Handle entries without parentheses (e.g., Region$$Table, .ARM.Collect$$...)
                    const tokens = rest.trim().split(/\s+/);
                    const lastToken = tokens[tokens.length - 1];
                    if (lastToken && !/^\d+$/.test(lastToken) && !/^[-*]+$/.test(lastToken)) {
                        section = lastToken;
                        func = extractFunc(lastToken);
                    }
                }

                currentExecRegion.entries.push({
                    addr,
                    size: sz,
                    kind,
                    attr,
                    object,
                    section,
                    func,
                });
                continue;
            }

            // Skip PAD entries (treated as gaps for free space calculation)
            if (PAD_RE.test(line)) { continue; }

            // Section separator ends entry parsing context
            if (SEPARATOR_RE.test(line.trim())) {
                currentExecRegion = null;
            }
        }

        // Image totals
        const roMatch = RO_TOTAL_RE.exec(line);
        if (roMatch) { totals.roSize = parseInt(roMatch[1], 10); continue; }
        const rwMatch = RW_TOTAL_RE.exec(line);
        if (rwMatch) { totals.rwSize = parseInt(rwMatch[1], 10); continue; }
        const romMatch = ROM_TOTAL_RE.exec(line);
        if (romMatch) { totals.romSize = parseInt(romMatch[1], 10); continue; }
    }

    return { execRegions, entryPoint, totals };
}

/**
 * Convert execution regions to MemoryRegion array.
 */
export function toMemoryRegions(result: ArmLinkListResult): MemoryRegion[] {
    return result.execRegions
        .filter(r => r.maxSize > 0)
        .map(r => ({
            name: r.name,
            origin: r.execBase,
            size: r.maxSize,
        }));
}

/**
 * Convert listing entries to ElfSection-compatible array.
 * Individual entries are preserved for accurate free-space calculation.
 */
export function toElfSections(result: ArmLinkListResult): ElfSection[] {
    const sections: ElfSection[] = [];

    for (const region of result.execRegions) {
        for (const entry of region.entries) {
            if (entry.size === 0) { continue; }
            const kindLower = entry.kind.toLowerCase();

            sections.push({
                name: entry.section || entry.object || `[${entry.kind}]`,
                type: 0,
                flags: 0,
                addr: entry.addr,
                size: entry.size,
                isAlloc: true,
                isWrite: entry.attr === 'RW',
                isExec: kindLower === 'code',
                isNoBits: kindLower === 'zero' || entry.attr === 'ZI',
            });
        }
    }

    return sections;
}

/**
 * Create aggregated SectionSummary by section name.
 * Groups entries with the same section name across all regions.
 */
export function toAggregatedSummary(result: ArmLinkListResult): SectionSummary[] {
    const groups = new Map<string, { minAddr: number; maxEnd: number; totalSize: number; type: string }>();

    for (const region of result.execRegions) {
        for (const entry of region.entries) {
            if (entry.size === 0) { continue; }
            const name = entry.section || entry.object || `[${entry.kind}]`;
            const type = (entry.attr === 'ZI' || entry.kind.toLowerCase() === 'zero')
                ? 'NOBITS'
                : (entry.kind.toLowerCase() === 'code' ? 'CODE' : (entry.attr === 'RW' ? 'DATA' : 'RODATA'));

            const existing = groups.get(name);
            if (existing) {
                existing.minAddr = Math.min(existing.minAddr, entry.addr);
                existing.maxEnd = Math.max(existing.maxEnd, entry.addr + entry.size);
                existing.totalSize += entry.size;
            } else {
                groups.set(name, {
                    minAddr: entry.addr,
                    maxEnd: entry.addr + entry.size,
                    totalSize: entry.size,
                    type,
                });
            }
        }
    }

    return Array.from(groups).map(([name, g]) => ({
        name,
        addr: g.minAddr,
        endAddr: g.maxEnd,
        size: g.totalSize,
        type: g.type,
    })).sort((a, b) => a.addr - b.addr);
}

/**
 * Object-level summary: groups all entries by object name across regions.
 * Returns total size and percentage of given totalSize for each object.
 */
export interface ObjectSummary {
    object: string;
    totalSize: number;
    codeSize: number;
    dataSize: number;
    roSize: number;
    bssSize: number;
    entries: { section: string; size: number; kind: string; region: string }[];
}

export function toObjectSummary(result: ArmLinkListResult): ObjectSummary[] {
    const groups = new Map<string, ObjectSummary>();

    for (const region of result.execRegions) {
        for (const entry of region.entries) {
            if (entry.size === 0) { continue; }
            const objName = entry.object || entry.section || `[${entry.kind}]`;

            let group = groups.get(objName);
            if (!group) {
                group = { object: objName, totalSize: 0, codeSize: 0, dataSize: 0, roSize: 0, bssSize: 0, entries: [] };
                groups.set(objName, group);
            }
            group.totalSize += entry.size;

            const kindLower = entry.kind.toLowerCase();
            if (entry.attr === 'ZI' || kindLower === 'zero') {
                group.bssSize += entry.size;
            } else if (kindLower === 'code') {
                group.codeSize += entry.size;
            } else if (entry.attr === 'RW') {
                group.dataSize += entry.size;
            } else {
                group.roSize += entry.size;
            }

            group.entries.push({
                section: entry.section || `[${entry.kind}]`,
                size: entry.size,
                kind: entry.kind,
                region: region.name,
            });
        }
    }

    return Array.from(groups.values()).sort((a, b) => b.totalSize - a.totalSize);
}

/**
 * Compute MemoryUsage directly from execution regions.
 * Unlike computeMemoryUsage (address-range matching), this uses the listing's
 * own region→entry association, avoiding cross-region miscounting when
 * address ranges overlap.
 */
export function toMemoryUsage(result: ArmLinkListResult): MemoryUsage[] {
    return result.execRegions
        .filter(r => r.maxSize > 0)
        .map(r => {
            const sections: MemoryUsageEntry[] = r.entries
                .filter(e => e.size > 0)
                .map(e => {
                    const kindLower = e.kind.toLowerCase();
                    return {
                        name: e.object || e.section || `[${e.kind}]`,
                        size: e.size,
                        addr: e.addr,
                        type: (e.attr === 'ZI' || kindLower === 'zero')
                            ? 'NOBITS'
                            : (kindLower === 'code' ? 'CODE' : (e.attr === 'RW' ? 'DATA' : 'RODATA')),
                        object: e.object || undefined,
                        section: e.section || undefined,
                        func: e.func || undefined,
                    };
                });

            // Sort by address to compute free spaces
            const addrSorted = [...sections].sort((a, b) => a.addr - b.addr);
            const freeSpaces: { addr: number; size: number }[] = [];
            let cursor = r.execBase;
            const regionEnd = r.execBase + r.maxSize;
            for (const sec of addrSorted) {
                const secEnd = Math.min(sec.addr + sec.size, regionEnd);
                if (sec.addr > cursor) {
                    freeSpaces.push({ addr: cursor, size: sec.addr - cursor });
                }
                cursor = Math.max(cursor, secEnd);
            }
            if (cursor < regionEnd) {
                freeSpaces.push({ addr: cursor, size: regionEnd - cursor });
            }

            // Compute used from actual occupied span (handles overlapping sections)
            const actualUsed = r.maxSize - freeSpaces.reduce((sum, f) => sum + f.size, 0);

            return {
                region: r.name,
                used: Math.min(actualUsed, r.maxSize),
                total: r.maxSize,
                sections: [...sections].sort((a, b) => b.size - a.size),
                freeSpaces: freeSpaces.filter(f => f.size >= 4),
                reportedUsed: r.size,
            };
        });
}
